{"name": "test_mul", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <test_04.Test_pytest_03 object at 0x00000167FA9D8BD0>\n\n    def test_mul(self):\n        a = 5\n        b = 4\n        result = a * b\n        print(\"Multiplication:\",result)\n        if result==25:\n            assert True\n        else:\n>           assert False\nE           assert False\n\ntest_04.py:10: AssertionError"}, "attachments": [{"name": "stdout", "source": "f6f98517-d28a-4da8-9eed-79740f1709bc-attachment.txt", "type": "text/plain"}], "start": 1690788151052, "stop": 1690788151052, "uuid": "8a68e96a-8da1-415a-9773-e8ee0de32c11", "historyId": "3d48961af63134f8a19afbb2a947cf21", "testCaseId": "3d48961af63134f8a19afbb2a947cf21", "fullName": "test_04.Test_pytest_03#test_mul", "labels": [{"name": "suite", "value": "test_04"}, {"name": "subSuite", "value": "Test_pytest_03"}, {"name": "host", "value": "Gaurav"}, {"name": "thread", "value": "1184-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_04"}]}